In [ ]:
pip install plotly

Requirement already satisfied: plotly in /home/sandosa/anaconda3/lib/python3.13/site-packages (5.24.1)
Requirement already satisfied: tenacity>=6.2.0 in /home/sandosa/anaconda3/lib/python3.13/site-packages (from plotly) (9.0.0)
Requirement already satisfied: packaging in /home/sandosa/anaconda3/lib/python3.13/site-packages (from plotly) (24.2)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

In [23]:
df = pd.read_csv("/home/sandosa/Desktop/Depi-Ai/CA-R5-S2S2-AI-/src/DA/pandas/work shope/Titanic.csv")

In [24]:
df.drop(['PassengerId','Name','Ticket'], axis =1 , inplace= True)
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [4]:
import plotly.express as px

In [5]:
fig = px.pie(df, names="Survived",
             title="<b>survived pie plot</b>",
             color_discrete_map={0: "red", 1: "green"}, 
             hole=0.4
             #color_discrete_sequence=px.colors.qualitative.Pastel
             )
fig.update_layout(annotations = [dict(text = 'Survived', font_size = 20,x = 0.5, y = 0.5 , showarrow = False)])
fig.show()

In [6]:
px.histogram(df, x="Survived", color="Sex", title="<b>Survived hist dist</b>", barmode="group")

In [7]:
import plotly.graph_objects as go

In [25]:
cat_cols = ["Survived", "Pclass", "Sex", "SibSp", "Parch", "Embarked" ]
df[cat_cols] = df[cat_cols].astype('category')

In [26]:
cat_cols = df.select_dtypes("category").columns
cat_cols

Index(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Embarked'], dtype='object')

In [10]:
from plotly.subplots import make_subplots
fig = make_subplots(rows=2, cols=3, subplot_titles=cat_cols)
for i, col in enumerate(cat_cols):
    fig.add_trace(go.Histogram(x=df[col], name=col), row=i//3+1, col=i%3+1)

fig.show()

In [31]:
x = df.drop("Survived", axis=1)


y = df["Survived"]
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 889, dtype: category
Categories (2, int64): [0, 1]

In [12]:
x= df.iloc[:,1:]

y = df.iloc[:,[0]]

In [ ]:
df = df.dropna(subset=["Embarked"])
df = df.drop("Cabin", axis=1)
median = df["Age"].median()
df["Age"] = df["Age"].fillna(median)

In [32]:
x.head()

  Pclass     Sex   Age SibSp Parch     Fare Embarked
0      3    male  22.0     1     0   7.2500        S
1      1  female  38.0     1     0  71.2833        C
2      3  female  26.0     0     0   7.9250        S
3      1  female  35.0     1     0  53.1000        S
4      3    male  35.0     0     0   8.0500        S

In [33]:
 pip install scikit-learn

Requirement already satisfied: scikit-learn in /home/sandosa/anaconda3/lib/python3.13/site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /home/sandosa/anaconda3/lib/python3.13/site-packages (from scikit-learn) (2.1.3)
Requirement already satisfied: scipy>=1.6.0 in /home/sandosa/anaconda3/lib/python3.13/site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in /home/sandosa/anaconda3/lib/python3.13/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/sandosa/anaconda3/lib/python3.13/site-packages (from scikit-learn) (3.5.0)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [34]:
from sklearn.preprocessing import MinMaxScaler

In [40]:
num_cols = df.select_dtypes("number").columns
num_cols
scaler = MinMaxScaler()
scaler.fit(x[num_cols])

MinMaxScaler()

In [41]:
x[num_cols] = scaler.transform(x[num_cols])
x.head()

  Pclass     Sex       Age SibSp Parch      Fare Embarked
0      3    male  0.271174     1     0  0.014151        S
1      1  female  0.472229     1     0  0.139136        C
2      3  female  0.321438     0     0  0.015469        S
3      1  female  0.434531     1     0  0.103644        S
4      3    male  0.434531     0     0  0.015713        S

In [42]:
pip install one-hot-encoder

Collecting one-hot-encoder
  Downloading one_hot_encoder-1.1.tar.gz (2.4 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: one-hot-encoder
  Building wheel for one-hot-encoder (pyproject.toml) ... done
  Created wheel for one-hot-encoder: filename=one_hot_encoder-1.1-py3-none-any.whl size=3538 sha256=75ec11f0b0677ccb827d990aab8ee212c432ecd2d09d017a5024540bd27f3ff3
  Stored in directory: /home/sandosa/.cache/pip/wheels/30/75/0b/d695f28141995bae7b75cae0e03ad7226ad39711963c210372
Successfully built one-hot-encoder
Installing collected packages: one-hot-encoder
Successfully installed one-hot-encoder-1.1

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [46]:
pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.11.0-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.14.0 in /home/sandosa/anaconda3/lib/python3.13/site-packages (from category_encoders) (2.1.3)
Requirement already satisfied: pandas>=1.0.5 in /home/sandosa/anaconda3/lib/python3.13/site-packages (from category_encoders) (2.2.3)
Requirement already satisfied: scikit-learn>=1.6.0 in /home/sandosa/anaconda3/lib/python3.13/site-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /home/sandosa/anaconda3/lib/python3.13/site-packages (from category_encoders) (1.15.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/sandosa/anaconda3/lib/python3.13/site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/sandosa/anaconda3/lib/python3.13/site-packages (from pandas>=1.0.5->category_encoders) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/sandosa/anaconda3/lib/python3.13/site-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: six>=1.5 in /home/sandosa/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in /home/sandosa/anaconda3/lib/python3.13/site-packages (from scikit-learn>=1.6.0->category_encoders) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/sandosa/anaconda3/lib/python3.13/site-packages (from scikit-learn>=1.6.0->category_encoders) (3.5.0)
Downloading category_encoders-2.11.0-py3-none-any.whl (107 kB)
Installing collected packages: category_encoders
Successfully installed category_encoders-2.11.0

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [ ]:
from category_encoders import OneHotEncoder

In [53]:
str_cols = ['Sex', 'Embarked']
encoder = OneHotEncoder(cols= str_cols , drop_invariant=True)
x = encoder.fit_transform(x)

In [54]:
x.head()

,Pclass,Sex_1,Sex_2,Age,SibSp,Parch,Fare,Embarked_1,Embarked_2,Embarked_3
0,3,1,0,0.271174,1,0,0.014151,1,0,0
1,1,0,1,0.472229,1,0,0.139136,0,1,0
2,3,0,1,0.321438,0,0,0.015469,1,0,0
3,1,0,1,0.434531,1,0,0.103644,1,0,0
4,3,1,0,0.434531,0,0,0.015713,1,0,0